
export const PROFIT_RATE_SELLING = 0.43;
export const PROFIT_RATE_GENERAL_DISCOUNT = 0.39;
export const PROFIT_RATE_SPECIAL_DISCOUNT = 0.36;
export const INFLATION_RATE_PER_10_MONTHS = 0.35;
export const INVENTORY_ALERT_THRESHOLD = 5;
